import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
const {chromium,webkit}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE_PATH).href);
const origin=process.env.DENTIX_PREVIEW_ORIGIN??'http://127.0.0.1:4181';
const output=process.env.DENTIX_QA_OUTPUT??'docs/qa/request30-model-2026-09-08';
const sizes=process.env.DENTIX_QA_SIZES?JSON.parse(process.env.DENTIX_QA_SIZES):[[390,844],[1440,900]];
const reports=[];
// Deliberately retain contradictory deprecated values: the browser must ignore them.
const services=[{id:'consult',name:'Консультація ортодонта',duration_minutes:30},{id:'procedure',name:'Лікування',duration_minutes:150},{id:'null-duration',name:'Обрана послуга',duration_minutes:null}].map(s=>({...s,category:'Ізольовані дані'}));
const links=services.map(s=>({service_id:s.id,doctor_id:'doctor',active:true,booking_mode:'CALLBACK_ONLY',reservation_duration_minutes:240,consultation_service_id:'hidden',buffer_before_minutes:60,buffer_after_minutes:60}));
for(const [engineName,engine] of Object.entries({chromium,webkit}).filter(([name])=>!process.env.DENTIX_QA_ENGINE||name===process.env.DENTIX_QA_ENGINE)){
 const browser=await engine.launch();
 try{for(const [width,height] of sizes){
  const page=await browser.newPage({viewport:{width,height}});page.setDefaultTimeout(20000);page.setDefaultNavigationTimeout(45000);const errors=[],requests=[];let firstConflict=true,conflictSlot=false,available=true,receiptStatus='AWAITING_CALLBACK';
  page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/api/public/**',async route=>{
   const req=route.request(),path=new URL(req.url()).pathname;let data;
   if(path.endsWith('/intake-status'))data={lead:{enabled:available,mode:available?'LIVE':'UNAVAILABLE',policyUrl:available?'https://example.org/fixture-policy':null,consentVersion:'fixture-v4'},timed:{enabled:available,mode:available?'LIVE':'UNAVAILABLE',policyUrl:available?'https://example.org/fixture-policy':null,consentVersion:'fixture-v4'}};
   else if(path.endsWith('/catalog'))data={mode:'LIVE_REQUESTS_READY',testOnly:false,timezone:'Europe/Kyiv',minDate:'2026-10-01',maxDate:'2026-10-30',services,doctors:[{id:'doctor',name:'Ізольований лікар',role_label:'Ізольовані дані'}],doctorServices:links};
   else if(path.endsWith('/availability'))data={date:'2026-10-01',provisionalMinutes:30,slots:[0,30,60].filter(n=>!conflictSlot||n!==0).map(n=>({startsAt:new Date(Date.parse('2026-10-01T10:00:00Z')+n*60000).toISOString(),endsAt:new Date(Date.parse('2026-10-01T10:30:00Z')+n*60000).toISOString(),localStart:n===0?'13:00':n===30?'13:30':'14:00',localEnd:n===0?'13:30':n===30?'14:00':'14:30'}))};
   else if(req.method()==='POST'){
    const body=req.postDataJSON();requests.push({path,body});assert.equal(body.consent,true);assert.equal(body.test_submission,undefined);assert.equal(req.headers()['x-dentix-qa'],undefined);for(const key of ['duration','duration_minutes','ends_at','endsAt','manual_end','booking_mode','buffer_before_minutes','buffer_after_minutes','requested_service_id'])assert.equal(body[key],undefined);
    if(path.endsWith('/leads'))data={message:'Дякуємо! Адміністратор зателефонує.'};
    else if(firstConflict){firstConflict=false;conflictSlot=true;return route.fulfill({status:409,json:{error:{code:'SLOT_NO_LONGER_AVAILABLE',message:'Час уже зайнятий. Оберіть інший.'}}});}
    else data={appointmentId:'fixture',reference:'FIXTURE-REQUEST',status:receiptStatus,revision:1,message:'Запит на запис отримано. Обраний час попередньо збережено. Адміністратор DENTIX зателефонує, щоб узгодити та підтвердити деталі.',serviceName:services.find(s=>s.id===body.service_id).name,startsAt:body.starts_at,endsAt:new Date(Date.parse(body.starts_at)+30*60000).toISOString()};
   }else data=[];
   await route.fulfill({json:{data}});
  });
  await page.goto(`${origin}/`,{waitUntil:'networkidle'});const trigger=page.getByRole('button',{name:'Записатися онлайн',exact:true}).first(),dialog=page.getByRole('dialog');
  async function next(){await dialog.getByRole('button',{name:'Далі',exact:true}).click();}
  for(const service of [...services,{...services[0],replayStatus:'CANCELLED'},{...services[1],replayStatus:'CONFIRMED'}]){
   receiptStatus=service.replayStatus??'AWAITING_CALLBACK';const expectConflict=firstConflict;conflictSlot=false;await trigger.click();await dialog.locator('.booking-options').getByText(service.name,{exact:true}).click();assert.equal(await dialog.getByRole('button',{name:'Далі',exact:true}).isEnabled(),true);assert.equal(await dialog.getByText(/Тривалість|Час уточнюється|DIRECT_SLOT|CONSULTATION_SLOT|CALLBACK_ONLY/).count(),0);await next();await dialog.getByText('Ізольований лікар',{exact:true}).click();await next();await dialog.locator('input[type=date]').fill('2026-10-01');
   for(const time of ['13:00','13:30','14:00'])await dialog.getByRole('button',{name:time,exact:true}).waitFor();await dialog.getByText(/Оберіть бажаний початок/).waitFor();await fs.mkdir(output,{recursive:true});if(service.id==='null-duration')await dialog.screenshot({path:`${output}/${engineName}-patient-grid-${width}.png`});await dialog.getByRole('button',{name:'13:00',exact:true}).click();await next();
   await dialog.getByLabel('Ім’я *',{exact:true}).fill('Олена Перевірка');await dialog.getByLabel('Телефон *',{exact:true}).fill('+380000000071');assert.equal(await dialog.getByRole('button',{name:'Далі',exact:true}).isDisabled(),true);await dialog.locator('input[type=checkbox]').check();if(width<=900)for(const input of await dialog.locator('input:not([type=checkbox])').all())assert.ok(await input.evaluate(e=>parseFloat(getComputedStyle(e).fontSize))>=16);await next();await dialog.getByText('Бажаний час',{exact:true}).waitFor();await dialog.getByRole('button',{name:'Надіслати запит'}).click();
   if(expectConflict){await dialog.getByRole('alert').waitFor();assert.equal(await dialog.getByRole('button',{name:'13:00',exact:true}).count(),0);await dialog.getByRole('button',{name:'13:30',exact:true}).click();await next();assert.equal(await dialog.getByLabel('Ім’я *',{exact:true}).inputValue(),'Олена Перевірка');await next();await dialog.getByRole('button',{name:'Надіслати запит'}).click();}
   await dialog.getByText('FIXTURE-REQUEST',{exact:true}).waitFor();if(receiptStatus==='AWAITING_CALLBACK')await dialog.getByText(/Це не тривалість лікування/).waitFor();else{await dialog.getByText(/Цей запит уже було збережено/).waitFor();assert.equal(await dialog.getByText(/Обраний час попередньо збережено на 30 хвилин/).count(),0);await dialog.locator('dd').getByText(receiptStatus==='CANCELLED'?'Скасовано':'Підтверджено',{exact:true}).waitFor();}assert.equal(await dialog.locator('dd').filter({hasText:service.name}).count(),1);assert.equal(requests.at(-1).body.service_id,service.id);if(service.id==='null-duration')await dialog.screenshot({path:`${output}/${engineName}-patient-confirmation-${width}.png`});await dialog.getByRole('button',{name:'Готово'}).click();console.log(engineName,width,service.id,'request30 PASS');
  }
  const timedPosts=requests.length;await trigger.click();await dialog.locator('.booking-options').getByText('Обрана послуга',{exact:true}).click();await dialog.getByRole('button',{name:'Залишити окрему заявку без вибору часу'}).click();assert.equal(await dialog.locator('input[type=date]').count(),0);await dialog.getByLabel('Ім’я *',{exact:true}).fill('Олена Перевірка');await dialog.getByLabel('Телефон *',{exact:true}).fill('+380000000071');await dialog.locator('input[type=checkbox]').check();await dialog.getByRole('button',{name:'Залишити заявку',exact:true}).click();await dialog.getByText(/Дякуємо!/).waitFor();assert.ok(requests.at(-1).path.endsWith('/leads'));assert.equal(requests.length,timedPosts+1);await dialog.getByRole('button',{name:'Закрити',exact:true}).click();
  available=false;await trigger.click();await dialog.getByText('Заявка не резервує час прийому.').waitFor();assert.equal(await dialog.locator('.booking-options').count(),0);assert.equal(await dialog.getByRole('button',{name:'Залишити заявку',exact:true}).isDisabled(),true);await dialog.getByRole('button',{name:'Закрити',exact:true}).click();assert.equal(await page.evaluate(()=>document.body.style.position),'');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)<=1);assert.ok(!/user-scalable|maximum-scale/.test(await page.locator('meta[name=viewport]').getAttribute('content')));assert.deepEqual(errors,[]);
  reports.push({engineName,width,height,pass:true,fixtureOnly:true,physicalDevice:false,legacyDurationsIgnored:[30,150,null],preferredGrid:['13:00','13:30','14:00'],timedPosts,leadPosts:1,consentRequired:true,privacyGatePreserved:true});await fs.writeFile(`${output}/patient-request30-ui.json`,JSON.stringify({scope:'Isolated API fixtures; no live mutations',reports},null,2));await page.close();
 }}finally{await browser.close();}
}
